### PR TITLE
feat: add unregister function to core

### PR DESCRIPTION
**Pull request by stevesims**
An `unregister` function can be useful, especially if your dev environment supports hot-reloading

adding in `unregister` thus allows for code like this:
```
register('registryKey', SomeItem);
if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.dispose(() => {
    unregister('registryKey', SomeItem);
  });
}
```
following this patter ensures that you'll only have one copy of the item stored in the registry

### CODE REVIEW

**Review by csabapalfi — APPROVED** [review]

**Comment by stevesims** [comment]
guh, wha?

build failing now, when it had been working before - apparently a module that's part of the build system is missing, which is odd.  you'd expect the module to be installed as a dependency via the yarn.lock.  this is all working for me locally - but i've not yet tried the build sequence stuff with `CI=true`

when i get the chance i'll try making a different PR to update tsdx (and other modules) to see if that works/fixes

**Comment by stevesims** [comment]
ok - discovered a bit more - this seems to be an issue related to node 12.18.3 - locally i was previously running 12.6.0.

having updated to node 12.18.3 i see this same issue locally 😢

**Comment by stevesims** [comment]
ok - fix is to kill and refresh the yarn.lock file - build now working

**Comment by csabapalfi** [comment]
👍 Nice

**Pull request merged**
